POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "google",
  "url": "https://google.com",
  "description": "구글입니다.",
  "children": [
    {
      "name": "google gemini",
      "url": "https://gemini.google.com/",
      "description": "구글 제미니입니다."
    }
  ]
}

###
POST http://localhost:8080/items
Content-Type: application/json

{
    "name": "google2",
    "url": "https://google.com",
    "description": "구글입니다.2"
}

###
GET http://localhost:8080/items?name=goo


###
GET http://localhost:8080/items/01966737-18c4-a2a3-66a1-5ef543a233c5

###
PATCH http://localhost:8080/items/01966737-18c4-a2a3-66a1-5ef543a233c5
Content-Type: application/json

{
  "description": "설명수정..5"
}